amqp unsub routine now works, make broker logic more robust
INTERSECT-SDK/python-sdk pull request #7
Opened 2024-07-16 14:29 UTC by Lance-Drane

Will probably add this to a v0.6.3 release since the public API does not change at all, but note that internally AMQP functions very differently.

## Possible changes needed for experiment controller

Whenever calling some of the ControlPlaneManager functions (add_subscription_channel and publish_message), you'll now need to add a `persist` boolean flag onto the calls - certain messages persist and certain messages don't.

## AMQP CHANGES

- unsubscribe actually works now (added another AMQP E2E test to prove it)
- Now use topic exchanges instead of fanout exchanges. Instead of creating an exchange for each topic like we were doing (and queues for each), we use a single hardcoded exchange. Some queues are meant to be dedicated (for example: Services will handle Userspace messages in their own dedicated queue, and INTERSECT Core Services will always use a dedicated queue for all messages), while other queues are meant to be transient (for example: when listening to events, Clients will create a temporary transient queue).

What I'd like to do in the future would be to create the exchanges, the dedicated queues, and the queue/exchange bindings on RabbitMQ (the server) instead of in the SDK (both Services and Clients act as RabbitMQ clients). This will allow us to configure AUTH on the broker itself by topic, and not "rely" on something using the SDK inappropriately reading/writing messages from certain dedicated queues.

## General Changes

Both the MQTT and the AMQP implementations are now more robust regarding reconnecting to the broker. Both will attempt to reconnect on failure, and both will automatically resubscribe to all topics they should be subscribed to once the reconnect is successful.

2024-07-17 02:51 UTC, marshallmcdonnell requested changes
Overall, LGTM!

I only have general questions about certain things to help my understanding.

Besides that, the failing tests related to the channel stuff are the only blockers right now.

Is this a "false negative" test?
Something wrong with the lifetime of the rmq broker during the testing?

2024-07-17 02:51 UTC, marshallmcdonnell commented on examples/1_hello_world_amqp/hello_client.py
> +logging.getLogger('pika').setLevel(logging.WARNING)
Just checking, are these the log levels we want for the examples? Just making sure this isn't carry over debug stuff.

Warning level seems perfectly fine but just wanting to double check.

2024-07-17 02:51 UTC, marshallmcdonnell commented on examples/1_hello_world_amqp/hello_service.py
> +logging.getLogger('pika').setLevel(logging.WARNING)
Just checking, are these the log levels we want for the examples? Just making sure this isn't carry over debug stuff.

Warning level seems perfectly fine but just wanting to double check.

2024-07-17 02:51 UTC, marshallmcdonnell commented on src/intersect_sdk/_internal/control_plane/brokers/broker_client.py
> +class BrokerClient(Protocol):
Just checking, looks like you made the switch from ABC -> Protocol like Gavin mentioned?

Overall, looks like you just remove the `@abstractmethod` decorators but everything else stays the same, right?

2024-07-17 18:21 UTC, Lance-Drane commented on src/intersect_sdk/_internal/control_plane/brokers/broker_client.py
> +class BrokerClient(Protocol):
Yeah I spent about 20-30 minutes looking in to it and it was a really easy fix. `BrokerClient` is a private interface and does not need any runtime checks (especially since we never use `isinstance(obj, BrokerClient)`), so Protocol is strictly superior for our usecase. If you want to add runtime support for `isinstance` and `issubclass` we can just use the `@runtime_checkable` annotation.

2024-07-17 19:58 UTC, Lance-Drane commented
> Besides that, the failing tests related to the channel stuff are the only blockers right now.
> 
> Is this a "false negative" test? Something wrong with the lifetime of the rmq broker during the testing?

I looked into it and what seemed to be happening is that a message on the AMQP channel would sometimes be published before the exchange was declared. This was specifically the "lifecycle startup" message being sent by the Service.

In theory this could happen with Clients as well, if they are publishing initial messages (if they are only waiting on events, this exception would never happen; only thing to be concerned about is whether or not the Client would get the event message). I had thought this was the original error before looking at the test exception stack trace (I missed it when developing because I wasn't arbitrarily removing exchanges at the time).

2024-07-18 01:22 UTC, marshallmcdonnell approved these changes
Awesome work! Thanks!

2024-07-18 18:47 UTC, merged