Multi-capability and svc2svc support for services
INTERSECT-SDK/python-sdk pull request #9
Opened 2024-07-31 19:38 UTC by Lance-Drane

From @MichaelBrim:

This changeset includes updates to enable each IntersectService instance to provide service for a set of capabilities, rather than just one. From the client perspective, the key difference is that operation names should be prepended with the advertised name of the capability providing the operation.

Also included is support for service-to-service requests, as is necessary to enable making external requests to other services/capabilities as part of the implementation of any service methods. An additional thread is used to process these external requests asynchronously from incoming request handlers.

2024-08-02 14:35 UTC, MichaelBrim commented on src/intersect_sdk/service.py
> +            self._delete_external_request(extreq.request_id)
yeah, that was a typo

2024-08-02 14:38 UTC, MichaelBrim commented on src/intersect_sdk/service.py
> +            self._external_requests_lock.release_lock()
yes, this should have the lock code.

2024-08-02 14:40 UTC, MichaelBrim commented on src/intersect_sdk/service.py
> +    def _process_external_requests(self) -> None:
that's fine. originally, I had capabilities calling this method on their parent service, but I eliminated the need for that

2024-08-02 14:46 UTC, MichaelBrim commented on src/intersect_sdk/service.py
> +            if extreq.response_fn is not None and extreq.error is None:
There is still a case here where the response may be None due to a wait timeout. In that case, there is no response to pass to the `extreq.response_fn`, so I would restore the first `if` statement and keep the updated code as the second (nested) `if`

2024-08-02 14:53 UTC, MichaelBrim requested changes
Most of the changes are good to go. I commented and resolved those conversations.

There is still one thing to be fixed. See my answer to question about `IntersectService._process_external_request()` response handling.

2024-08-02 15:34 UTC, gecage952 commented
Overall, looks good to me as well with only a couple of pretty minor comments.

2024-08-02 15:35 UTC, gecage952 commented on src/intersect_sdk/_internal/messages/userspace.py
>  from services they explicitly messaged.
This doc should probably be updated.

2024-08-02 21:07 UTC, Lance-Drane commented on src/intersect_sdk/service.py
> +            if extreq.response_fn is not None and extreq.error is None:
I added an explicit property to `_ExternalRequest` called `got_valid_response` to handle the wait timeout issue you mentioned - this property is initially False but gets set to True once we save the message payload value to the "response" property. Since the message payload's value can be so dynamic (and can end up being set to None even with a valid svc2svc request), I don't like inspecting that specific value for control flow.

2024-08-02 21:09 UTC, Lance-Drane commented on src/intersect_sdk/_internal/messages/userspace.py
>  from services they explicitly messaged.
Documentation should be updated now. Since this is an internal module the target audience is SDK developers and architects, not end users.

2024-08-02 21:22 UTC, Lance-Drane commented
> So basically services use `create_external_request` to just send messages to other services? Seems nice. 

Yep! Added this in one of the commits today. The API may be a little awkward since it returns a list of UUIDs instead of one UUID, but in practice you should be able to just reference `[0]` (and that's if you even need the UUID in your Capability, I don't think you do)

> Would it make sense to rename `IntersectClientMessageParams` since it's not exclusively being used by clients anymore? Maybe, just remove the client part.

I ended up renaming this to `IntersectDirectMessageParams` to draw a distinction between an explicit Service object and an explicit Client object. Additionally, I reorganized the callback modules into `client_callback_definitions`, `service_callback_definitions`, and `shared_callback_definitions` to more explicitly organize these between Client and Service - `IntersectDirectMessageParams` is in the shared module.

2024-08-08 14:45 UTC, gecage952 commented
This all looks good to me.

2024-08-08 14:46 UTC, gecage952 approved these changes

2024-08-12 17:59 UTC, marshallmcdonnell commented
Just to check, @MichaelBrim, are you good with this now?

I think once we have your approval in, we are good to go with a merge!

Mainly checking in since this is a current blocker for @gecage952

2024-08-12 18:22 UTC, MichaelBrim approved these changes
Looks like the `_ExternalReques.got_valid_response` addition addresses my only concern. Good to go from my perspective.

2024-08-12 19:32 UTC, Lance-Drane commented
I'd ideally like to have an E2E test in but we can merge this and cut an early 0.7.0 release.

2024-08-12 20:53 UTC, MichaelBrim commented
@Lance-Drane I can probably make some time to do that this week, but no promises. I'm also on travel next week.

2024-08-12 21:08 UTC, Lance-Drane commented
@MichaelBrim thanks, if you're only able to partially complete it just push it to a branch and myself, Greg, or Marshall can take a look at it.

2024-08-21 15:41 UTC, Lance-Drane commented
OK, E2E test is in - had to fix a minor issue with how the service was cleaning up external requests but otherwise everything looks good. Thank you to both @gecage952 and @MichaelBrim for the contributions! I will merge this and release v0.7.0 shortly.

2024-08-21 16:28 UTC, merged